# Generated by Django 3.2.8 on 2021-10-28 23:21

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ireporterApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=43)),
                ('description', models.TextField(max_length=100)),
                ('status', models.CharField(choices=[('received', 'received'), ('investigating', 'investigating'), ('rejected', 'rejected'), ('resolved', 'resolved')], default='received', max_length=20)),
                ('redFlag_image', models.ImageField(blank=True, null=True, upload_to=ireporterApp.models.redflag_image_upload)),
                ('redFlag_video', models.FileField(blank=True, max_length=4000, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to=ireporterApp.models.redflag_video_upload, validators=[cloudinary_storage.validators.validate_video])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('redFlag_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ireporterApp.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=100)),
                ('status', models.CharField(choices=[('received', 'received'), ('investigating', 'investigating'), ('rejected', 'rejected'), ('resolved', 'resolved')], default='received', max_length=20)),
                ('intervention_image', models.ImageField(upload_to=ireporterApp.models.intervention_image_upload)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ireporterApp.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
