# Generated by Django 3.2.8 on 2021-10-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ireporterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redflag',
            name='status',
            field=models.CharField(default='received', max_length=20),
        ),
    ]
