# Generated by Django 3.2.8 on 2021-10-20 19:20

from django.db import migrations, models
import ireporterApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ireporterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redflag',
            name='redFlag_image',
            field=models.ImageField(blank=True, null=True, upload_to=ireporterApp.models.redflag_image_upload),
        ),
    ]
